---
name: pumrporder:IDPRETAG
clusters:
  pumrporderIDPRETAG:
    services:
      breed:
        name: pumrporder:IDPRETAG
        deployable: partsunlimitedmrp/orderapi:IDPRETAG
        ports:
          webport: 8080/http
        environment_variables:
            MONGO_HOST: "pumrpdatabase.pumrpdatabase.marathon.mesos"
      scale:
        cpu: 1       
        memory: 1024MB
        instances: 1
